"""diario_hk_sync

Revision ID: 6677af61441c
Revises: 871fe89fe31f
Create Date: 2026-04-21 15:07:16.705841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6677af61441c'
down_revision: Union[str, None] = '871fe89fe31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diario_hk_sync',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('hk_uuid', sa.UUID(), nullable=True),
    sa.Column('pending_write_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pending_write_id'], ['pending_writes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'type', name='uq_diario_hk_sync_date_type')
    )
    op.create_index('idx_diario_hk_sync_pending', 'diario_hk_sync', ['pending_write_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_diario_hk_sync_pending', table_name='diario_hk_sync')
    op.drop_table('diario_hk_sync')
    # ### end Alembic commands ###
