"""lab_analytes + lab_analyte_aliases

Revision ID: c2b8d5103f22
Revises: b1a7c4f02e11
Create Date: 2026-04-23 00:00:01.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2b8d5103f22'
down_revision: Union[str, None] = 'b1a7c4f02e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'lab_analytes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('slug', sa.Text(), nullable=False),
        sa.Column('display_name_it', sa.Text(), nullable=False),
        sa.Column('category', sa.Text(), nullable=False),
        sa.Column('specimen', sa.Text(), nullable=False, server_default='blood'),
        sa.Column('value_type', sa.Text(), nullable=False, server_default='numeric'),
        sa.Column('unit_canonical', sa.Text(), nullable=True),
        sa.Column('ref_low', sa.Numeric(), nullable=True),
        sa.Column('ref_high', sa.Numeric(), nullable=True),
        sa.Column('ref_text', sa.Text(), nullable=True),
        sa.Column('sex_specific', sa.Text(), nullable=True),
        sa.Column('loinc_code', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_lab_analytes_slug'),
    )

    op.create_table(
        'lab_analyte_aliases',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('analyte_id', sa.Integer(), nullable=False),
        sa.Column('alias', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['analyte_id'], ['lab_analytes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('alias', name='uq_lab_analyte_aliases_alias'),
    )
    # Functional index — not auto-generated by Alembic.
    op.execute(
        "CREATE INDEX ix_lab_aliases_lower "
        "ON lab_analyte_aliases (LOWER(alias))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_lab_aliases_lower")
    op.drop_table('lab_analyte_aliases')
    op.drop_table('lab_analytes')
